config/routes.rb
Rails.application.routes.draw do
  get 'employees/index'
  get 'employees/show'
  post 'employees/edit'
  post 'employees/new'
  put 'employees/update'
  get 'employees/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :employees
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = EmployeeDetail.all;
  end

  def show
    @employee = EmployeeDetail.find(params[:id])
  end

  def new
    @employee = EmployeeDetail.new
  end

  def create
    employee = EmployeeDetail.create(employee_params)
    redirect_to employees_path()
  end
   def edit
    @employee = EmployeeDetail.find(params[:id])
 end
  def update
    @employee = EmployeeDetail.find(params[:id]) 
    @employee.update(employee_params)
    redirect_to employees_path
  end
  def destroy
    @employee = EmployeeDetail.find(params[:id]) 
    @employee.destroy
    redirect_to employees_path


  end
 private
 def employee_params
  params.require(:employeeDetail).permit(:name,:age,:gender,:designation)
 end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/destroy.html.erb
<h1>Employees#destroy</h1>
<p>Find me in app/views/employees/destroy.html.erb</p>

app/views/employees/edit.html.erb
<h3>Update a Employee</h3>
<%= form_with model: @EmployeeDetail do |f|%>
    <%= f.text_field :name,placeholder:"Enter the name" %><br>
    <%= f.number_field :age,placeholder:"Enter the age"%><br>
    <%= f.text_field :gender,placeholder:"Enter the gender" %><br>
    <%= f.text_field :designation,placeholder:"Enter the designation" %><br>
    <%= f.submit %>
    <% end %>
  

app/views/employees/index.html.erb
<table border 1>
<% EmployeeDetail.all.each do |emp|%>
<tr>
<td><%= link_to emp.name, employee_path(emp) %></td>
<td><%= button_to 'Edit',edit_employee_path(emp), method:'get' %></td>
<td><%= button_to 'Remove',employee_path(emp), method:'delete', data:{ confirm:"Are you sure to delete"} %></td>
</tr>
    
    <% end %>
    <%= link_to "Add New Employee",new_employee_path %>
</table>

app/views/employees/new.html.erb
<h3>Create a Employee</h3>
<%= form_with model: @EmployeeDetail do |f|%>
    <%= f.text_field :name,placeholder:"Enter the name" %><br>
    <%= f.number_field :age,placeholder:"Enter the age"%><br>
    <%= f.text_field :gender,placeholder:"Enter the gender" %><br>
    <%= f.text_field :designation,placeholder:"Enter the designation" %><br>
    <%= f.submit %>
    <% end %>
  

app/views/employees/show.html.erb
<h1>Employee Details</h1>
<h2><%= @employee.name %></h2>
<h2><%= @employee.age %></h2>
<h2><%= @employee.gender %></h2>
<h2><%= @employee.designation %></h2>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>